### ISSUE TITLE
Setup Documentation

### ISSUE THREAD

**Issue by pixeline** [tommcfarlin/WordPress-Plugin-Boilerplate#251]
Hi!
I'm trying to rewrite an old plugin of mine and it seems like a good idea to use the WPP Boilerplate. Now, I'm a bit confused as to... names. 

Am I supposed to rename all function that have "plugin_name" or "Plugin_Name"  ? In the idea that this boilerplate gets you up and running as quickly as possible, I figured that would be a great first step. But there are filenames, functions and class names involved.

I have read you are looking to publish some documentation. That would be awesome. I don't think you need that much. A Quick Setup guide would do, and then useful links (plugin hooks,..) to the WP Codex. May I suggest you use the Wiki Github offers alongside this repo? No need to reinvent the wheel.
I'll contribute happily (once i've found the best way to go at it).

**Comment by tommcfarlin** [comment]
Hey @pixeline,

All good questions. To answer them in order:

> Am I supposed to rename all function that have "plugin_name" or "Plugin_Name" ? In the idea that this boilerplate gets you up and running as quickly as possible, I figured that would be a great first step. But there are filenames, functions and class names involved.

Yes. One easy way to do that is to use [this generator](http://wppb.me).

> I have read you are looking to publish some documentation. That would be awesome.

Yes - I'll have an announcement about this later in the month that'll cover this in more detail, but I'm going to start off with a few videos and then get down into documentation.

> A Quick Setup guide would do, and then useful links (plugin hooks,..) to the WP Codex. May I suggest you use the Wiki Github offers alongside this repo? No need to reinvent the wheel.
I'll contribute happily (once i've found the best way to go at it).

I won't be using the GitHub resources for this. Instead, I'll have a theme setup on the Plugin Boilerplate homepage that includes all of the information. This is to make is as accessible as possible to those who aren't familiar with GitHub but still want to get up and running with the Boilerplate and WordPress.

I'm beginning work on this during this month with a goal of having a bunch of content ready for it this quarter so stay tuned for that.

I'll also be announcing it via [my blog](http://tommcfarlin.com).

Thanks so much for your input!

**Comment by pixeline** [comment]
@tommcfarlin Awesome! I didn't dare to dream of a generator, and there you have it! Thank you very much for all !

**Comment by joelataylor** [comment]
@tommcfarlin there's no way you could drop us some "unfinished" docs/videos? I'm in desperate need in direction pointing. :)

**Comment by tommcfarlin** [comment]
@joelataylor I'd love to be able to to say yes, but I'm in the process of recording some of the videos now and don't want to share anything until things are in a more complete state :).

Right now, I'm looking at having the videos and the course (that will air through a WordPress service) towards the end of the month with the online documentation starting after that.

**Comment by oytuntez** [comment]
@tommcfarlin, I think we can put the generator link on the README file, don't you think? It looks like an amazing tool!
