### ISSUE TITLE
Plugin options and views?

### ISSUE THREAD

**Issue by fbm-static** [tommcfarlin/WordPress-Plugin-Boilerplate#257]
Hi, 

1. how would you go into setting the plugin options?

Should I be making another class for this?

2. how to render views/partials?

Thanks! I'm a wordpress plugin development newbie and your replies and views on this would greatly be impactful.

**Comment by tommcfarlin** [comment]
1. This all depends on how you want to set the options, but they would be set in the `admin` directory and likely read from both the `admin` and the `public` directory (depending on what they control).

2. I usually use a `display` method that is a callback from one of the API functions (like with `add_meta_box`) and then do an `include_once` on the partial file.
