### ISSUE TITLE
Can't create Custom Post Type when activate

### ISSUE THREAD

**Issue by mrkyt** [tommcfarlin/WordPress-Plugin-Boilerplate#261]
I try add to class Activator:
<pre>
public static function activate() {
        add_action( 'init', array( get_called_class(), 'create_custom_post_type' ),1 );
        do_action( 'init' );
}
public static function create_custom_post_type()
{
        // Create AFS post type
        $labels = array(
            'name' => __( 'Field&nbsp;Groups', 'afs' ),
            'singular_name' => __( 'Advanced Frontend Submit Fields', 'afs' ),
            'add_new' => __( 'Add New' , 'afs' ),
            'add_new_item' => __( 'Add New Field Group' , 'afs' ),
            'edit_item' =>  __( 'Edit Field Group' , 'afs' ),
            'new_item' => __( 'New Field Group' , 'afs' ),
            'view_item' => __('View Field Group', 'afs'),
            'search_items' => __('Search Field Groups', 'afs'),
            'not_found' =>  __('No Field Groups found', 'afs'),
            'not_found_in_trash' => __('No Field Groups found in Trash', 'afs'),
        );

        register_post_type('afs', array(
            'labels' => $labels,
            'public' => false,
            'show_ui' => true,
            '_builtin' =>  false,
            'capability_type' => 'page',
            'hierarchical' => true,
            'rewrite' => false,
            'query_var' => "afs",
            'supports' => array(
                'title',
            ),
            'show_in_menu'  => false,
        ));
}
</pre>
And it not working! Please help me

**Comment by slushman** [comment]
Here's the way I've created a custom post type using boilerplate 3:

In the class-plugin-name.php file, in define_admin_hooks(), put something like:

$this->loader->add_action( 'init', $plugin_admin, 'create_custom_post_type' );

Move your create_custom_post_type() function into the class-plugin-name-admin.php file in the admin folder. That should do it.

**Comment by mrkyt** [comment]
Awesome! It' work! Thank you so much!
But, i have one question:
<pre>
public static function activate() {
// What 's coding here?
}
</pre>

Thank you and sory my bad EL.

**Comment by slushman** [comment]
I've yet to find anything to put into the activate() function, but I'm still scratching the surface of what can be done with this boilerplate.

If I understand correctly, you want the CPT (and its menu) to deactivate when the plugin deactivates? It should just do that automatically, at least it has for me.

**Comment by mrkyt** [comment]
I use like you and i added custom post type successfuly, but i want when i deactivate custom post type must remove. Please tell me your way?

**Comment by eablokker** [comment]
You do not need to deactivate custom post types, they will be gone when you deactivate the plugin. However any custom posts will still be in the database, you just won't be able to see them. They will return when you re-activate the plugin.

**Comment by mrkyt** [comment]
@eablokker Thank you. What anything to put into the activate() function? Do you know?

**Comment by eablokker** [comment]
You might not need to put anything there. It totally depends on what kind of plugin you're building.

**Comment by mrkyt** [comment]
Thank you!

**Comment by tommcfarlin** [comment]
The `activate` and `deactivate` functions are normally used to prepare custom files, tables, or any other things that the plugin may need before it actually executes, and that it needs to remove upon uninstallation.

You shouldn't have to worry about using it when there are things you can apply to hooks (like the `init` hook used earlier in this thread).

The example given above by registering the custom post type with the loader is correct. These are the types of things that I'm looking to have documented in the near future so thanks for opening an issue and discussing it here.

**Comment by jjeaton** [comment]
@mrkyt the problem with the initial activation code is that when the activation hook runs, it's after the `init` hook has run, so hooking into `init` from the activation hook won't do anything.

You don't need to register the CPT within the activation function *unless* you need rewrite rules to be added via `flush_rewrite_rules()` on activation. In that case, you'll want to register the CPT normally, via the loader on the `init` hook, and also re-register it within the activation function and call `flush_rewrite_rules()` to add the CPT rewrite rules.
